[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:pulseaudio]
command=/bin/sh /opt/ra2/start-pulseaudio.sh
priority=5
autorestart=true
startsecs=2
environment=XDG_RUNTIME_DIR="/tmp/pulse-runtime",PULSE_RUNTIME_PATH="/tmp/pulse-runtime/pulse",PULSE_SERVER="unix:/tmp/pulse/native"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:xvfb]
command=/bin/sh /opt/ra2/start-xvfb-ultra.sh
priority=10
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:openbox]
command=/bin/sh /opt/ra2/start-openbox-ultra.sh
priority=20
autorestart=true
startsecs=2
environment=DISPLAY=":1"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:stream-gateway]
command=/bin/sh /opt/ra2/start-stream-gateway.sh
priority=40
autorestart=unexpected
exitcodes=0
startsecs=3
startretries=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:game]
command=/bin/sh /opt/ra2/start-game-ultra.sh
directory=/home/commander/game_assets
priority=50
autorestart=true
startsecs=10
startretries=20
environment=DISPLAY=":1",XDG_RUNTIME_DIR="/tmp/pulse-runtime",PULSE_RUNTIME_PATH="/tmp/pulse-runtime/pulse",PULSE_SERVER="unix:/tmp/pulse/native",WINEDLLOVERRIDES="mscoree=d;mshtml=d;ddraw=n,b;wsock32=n,b",LIBGL_ALWAYS_SOFTWARE="1"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
