#include <gst/gst.h>
#include <gst/webrtc/webrtc.h>
#include <gst/sdp/sdp.h>
#include <string.h>
static GMainLoop *loop; static GstElement *webrtc;
static gboolean quit_loop(gpointer data){g_main_loop_quit((GMainLoop*)data);return G_SOURCE_REMOVE;}
static void on_offer_created(GstPromise *promise,gpointer user_data){const GstStructure *reply=gst_promise_get_reply(promise);GstWebRTCSessionDescription *offer=NULL;if(!reply||!gst_structure_get(reply,"offer",GST_TYPE_WEBRTC_SESSION_DESCRIPTION,&offer,NULL)||!offer){g_printerr("NO OFFER\n");if(loop)g_main_loop_quit(loop);return;}gchar *text=gst_sdp_message_as_text(offer->sdp);g_print("OFFER_LEN=%zu\n",strlen(text));g_print("%.500s\n",text);GstPromise *local=gst_promise_new();g_signal_emit_by_name(webrtc,"set-local-description",offer,local);gst_promise_wait(local);g_print("LOCAL_SET\n");gst_promise_unref(local);g_free(text);gst_webrtc_session_description_free(offer);gst_promise_unref(promise);if(loop)g_main_loop_quit(loop);}
static gboolean make_offer(gpointer data){GstPromise *promise=gst_promise_new_with_change_func(on_offer_created,NULL,NULL);g_signal_emit_by_name(webrtc,"create-offer",NULL,promise);return G_SOURCE_REMOVE;}
static void on_negotiation_needed(GstElement *element,gpointer user_data){g_print("NEGOTIATION_NEEDED\n");g_idle_add(make_offer,NULL);} 
int main(int argc,char **argv){gst_init(&argc,&argv);GError *error=NULL;const gchar *desc="webrtcbin name=sendrecv bundle-policy=max-bundle latency=0 stun-server=stun://stun.l.google.com:19302 ximagesrc use-damage=false show-pointer=true do-timestamp=true display-name=:1 ! videorate max-rate=30 ! videoscale method=nearest-neighbour ! video/x-raw,width=1280,height=720,framerate=30/1 ! videoconvert ! queue max-size-buffers=1 max-size-bytes=0 max-size-time=0 leaky=downstream ! vah265enc bitrate=1200 key-int-max=30 ! h265parse config-interval=-1 ! rtph265pay pt=96 config-interval=-1 ! queue max-size-buffers=1 max-size-bytes=0 max-size-time=0 leaky=downstream ! application/x-rtp,media=video,encoding-name=H265,payload=96 ! sendrecv. tcpclientsrc host=127.0.0.1 port=4711 do-timestamp=true ! rawaudioparse use-sink-caps=false format=pcm pcm-format=s16le sample-rate=44100 num-channels=2 ! audioconvert ! audioresample quality=0 ! queue max-size-buffers=1 max-size-bytes=0 max-size-time=0 leaky=downstream ! opusenc bitrate=96000 bitrate-type=0 complexity=0 frame-size=10 audio-type=restricted-lowdelay inband-fec=false dtx=false ! rtpopuspay pt=97 ! queue max-size-buffers=1 max-size-bytes=0 max-size-time=0 leaky=downstream ! application/x-rtp,media=audio,encoding-name=OPUS,payload=97 ! sendrecv.";GstElement *pipeline=gst_parse_launch(desc,&error);if(!pipeline){g_printerr("parse error: %s\n",error->message);return 2;}webrtc=gst_bin_get_by_name(GST_BIN(pipeline),"sendrecv");g_signal_connect(webrtc,"on-negotiation-needed",G_CALLBACK(on_negotiation_needed),NULL);gst_element_set_state(pipeline,GST_STATE_PLAYING);loop=g_main_loop_new(NULL,FALSE);g_timeout_add_seconds(10,quit_loop,loop);g_main_loop_run(loop);gst_element_set_state(pipeline,GST_STATE_NULL);gst_object_unref(webrtc);gst_object_unref(pipeline);return 0;}
