[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:pulseaudio]
command=/bin/sh /opt/ra2/start-pulseaudio.sh
priority=5
autorestart=true
startsecs=2
environment=XDG_RUNTIME_DIR="/tmp/pulse-runtime",PULSE_RUNTIME_PATH="/tmp/pulse-runtime/pulse",PULSE_SERVER="unix:/tmp/pulse/native"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 %(ENV_RESOLUTION)sx16 -nolisten tcp
priority=10
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:openbox]
command=/usr/bin/openbox-session
priority=20
autorestart=true
startsecs=2
environment=DISPLAY=":1"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:x11vnc]
command=/bin/sh /opt/ra2/start-x11vnc.sh
priority=30
autorestart=unexpected
exitcodes=0
startsecs=2
startretries=1
environment=DISPLAY=":1"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:audio-proxy]
command=/bin/sh /opt/ra2/audio-proxy.sh -l 5711
priority=35
autorestart=unexpected
exitcodes=0
startsecs=0
startretries=1
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:latency-proxy]
command=/bin/sh /opt/ra2/latency-proxy.sh -l 5721
priority=36
autorestart=unexpected
exitcodes=0
startsecs=0
startretries=1
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:websockify]
command=/bin/sh /opt/ra2/start-websockify.sh
priority=40
autorestart=unexpected
exitcodes=0
startsecs=2
startretries=1
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:webrtc-media]
command=/bin/sh /opt/ra2/start-webrtc.sh
priority=41
autorestart=unexpected
exitcodes=0
startsecs=5
startretries=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:webrtc-input]
command=/bin/sh /opt/ra2/start-input-proxy.sh
priority=42
autorestart=unexpected
exitcodes=0
startsecs=2
startretries=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:game]
command=/opt/wine/bin/wine /home/commander/game_assets/%(ENV_GAME_EXE)s -SPEEDCONTROL
directory=/home/commander/game_assets
priority=50
autorestart=true
startsecs=10
startretries=3
environment=DISPLAY=":1",XDG_RUNTIME_DIR="/tmp/pulse-runtime",PULSE_RUNTIME_PATH="/tmp/pulse-runtime/pulse",PULSE_SERVER="unix:/tmp/pulse/native",WINEDLLOVERRIDES="mscoree=d;mshtml=d;ddraw=n,b;wsock32=n,b",LIBGL_ALWAYS_SOFTWARE="1"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
